apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ahammedejaz/flask-static-demo:latest
        ports:
        - containerPort: 80