name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          cd app
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Run your tests here. For example:
          source venv/bin/activate
          pytest

  docker-build-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (multi-arch)
        run: |
          docker buildx build --no-cache \
            --platform linux/amd64,linux/arm64 \
            -t ahammedejaz/flask-static-demo:latest \
            --push \
            -f docker/Dockerfile .

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: helical-cascade-453411-b5
          export_default_credentials: true

      - name: Install GKE Auth Plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials my-standard-cluster --zone us-central1-a --project helical-cascade-453411-b5

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Rollout Restart Deployment
        run: |
          kubectl rollout restart deployment/flask-app -n monitoring

      - name: Get External IP of Service
        run: |  
          EXTERNAL_IP=$(kubectl get svc flask-service -n monitoring -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Application is accessible at: http://${EXTERNAL_IP}"
          # Optionally verify that the image has been updated.

      - name: Verify Image Update
        run: |
            kubectl get pods -n monitoring -o jsonpath='{range .items[*]}{.metadata.name}{" - "}{.status.containerStatuses[*].imageID}{"\n"}{end}'